use_frameworks!

target 'PhotosKit_Example' do
  pod 'PhotosKit', :path => '../'

  target 'PhotosKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
