use_frameworks!
platform :ios,'9.0'
target 'PhotosKit_Example' do
  pod 'PhotosKit', :path => '../'

  target 'PhotosKit_Tests' do
    inherit! :search_paths
#    pod 'PhotosKit', :path => '../', :testspecs => ['Tests']
#    pod 'PhotosKit', :testspecs => ['Tests']
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
